[package]
name = "audiotoolbox-sys"
version = "0.1.0"
authors = ["Duane Bailey <bailey.d.r@gmail.com>"]
build = "build.rs"


[dependencies]

core-foundation = "0.3.0"
core-foundation-sys = "0.3.1"
libc = "0.2.23"

[build-dependencies]

bindgen = "0.23"

